### ISSUE TITLE
premiers tests

### ISSUE THREAD

**Issue by akakeronos** [dtc-innovation/anonymisation-document-budgetaire#21]
Je viens d'essayer d'utiliser votre outil. Voilà un premier retour infructueux pour l'instant

PS D:\Donnees\Documents\GitHub\anonymisation-document-budgetaire> npm install anon-doc-budg -g
C:\Users\pascal romain\AppData\Roaming\npm\anon-doc-budg -> C:\Users\pascal romain\AppData\Roaming\npm\node_modules\anon-doc-budg\bin\index.js
C:\Users\pascal romain\AppData\Roaming\npm
`-- anon-doc-budg@1.1.0

PS D:\Donnees\Documents\GitHub\anonymisation-document-budgetaire> ./anon-doc-budg --in ..\..\..\..\cloud\boxGironde\FLUX-XML-TOTEM\CA --out ..\..\..\..\cloud\boxGironde\FLUX-XML-TOTEM\CA\anon
./anon-doc-budg : Le terme «./anon-doc-budg» n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou programme exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès est correct et réessayez.
Au caractère Ligne:1 : 1
+ ./anon-doc-budg --in ..\..\..\..\cloud\boxGironde\FLUX-XML-TOTEM\CA --out ..\..\ ...
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (./anon-doc-budg:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

J'ai essayé aussi avec npm anon-doc-budg sans plus de succès.

**Comment by DavidBruant** [comment]
Normallement, après `npm install anon-doc-budg -g`, il suffit de faire `anon-doc-budg --in ... --out ...`.
Il n'y a pas de `./` à mettre avant.

De ce que je lis de la commande que tu fournis, j'ai l'impression que le dossier d'anonymisation est un sous-dossier. Je soupçonne que ça ne va pas marcher en l'état actuel de l'outil. Il vaudrait mieux essayer avec un dossier "frère/sœur". Je vais faire une issue pour que ce cas marche un jour.

**Comment by DavidBruant** [comment]
Sur "l'invite de commande" par défaut de Windows 7, avec Node déjà installé, j'ai obtenu le résultat suivant en tapant les commandes `npm install anon-doc-budg -g` puis `anon-doc-budg` : 

````sh
Microsoft Windows [version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Tous droits réservés.

C:\Users\David>npm install anon-doc-budg -g
C:\Users\David\AppData\Roaming\npm\anon-doc-budg -> C:\Users\David\AppData\Roami
ng\npm\node_modules\anon-doc-budg\bin\index.js
+ anon-doc-budg@1.1.0
added 10 packages in 13.665s


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.5.1 → 5.6.0    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯


C:\Users\David>anon-doc-budg
Error: Input and Output directories are mandatory.

  Usage: index --in <dossier> --out <dossier>


  Options:

    -V, --version    output the version number
    -i, --in <dir>   Input directory
    -o, --out <dir>  Output directory
    -h, --help       output usage information

C:\Users\David>
````

Donc visiblement, ça a l'air de marcher sur Windows

@akakeronos Que vois-tu en tapant ces 2 commandes à la suite ?
Quelle est ta configuration ?

**Comment by akakeronos** [comment]
je suis en windows 8 

PS D:\Donnees\Documents\GitHub\anonymisation-document-budgetaire> npm install anon-doc-budg -g
C:\Users\pascal romain\AppData\Roaming\npm\anon-doc-budg -> C:\Users\pascal romain\AppData\Roaming\npm\node_modules\anon-doc-budg\bin\index.js
C:\Users\pascal romain\AppData\Roaming\npm
`-- anon-doc-budg@1.1.0

PS D:\Donnees\Documents\GitHub\anonymisation-document-budgetaire> anon-doc-budg
anon-doc-budg : Le terme «anon-doc-budg» n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou programme exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès est correct et réessayez.
Au caractère Ligne:1 : 1
+ anon-doc-budg
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (anon-doc-budg:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS D:\Donnees\Documents\GitHub\anonymisation-document-budgetaire>

**Comment by akakeronos** [comment]
je suis passé en npm 5.6 mais pas mieux

**Comment by DavidBruant** [comment]
Je vais y aller au pif. "PS" suggère que tu utilises PowerShell sur Windows.
Normalement, quand on installe Node.js sur Windows, on a accès à une autre console, Est-ce que tu peux essayer avec la console Node, voir si ça marche mieux ?

**Comment by DavidBruant** [comment]
![commande node](https://user-images.githubusercontent.com/165829/34571922-38664cf6-f170-11e7-8cb3-fbb04ac18ef8.png)

**Comment by akakeronos** [comment]
ok. Pas de bol je viens d'essayer sur mon serveur ubuntu 14.04 et il y a un problème à l'installation de node.js https://github.com/nodejs/node-v0.x-archive/issues/3911

**Comment by akakeronos** [comment]
mieux :)
![image](https://user-images.githubusercontent.com/10322028/34572802-9f91c886-f172-11e7-9169-b4661adcbb19.png)

**Comment by akakeronos** [comment]
C'est bon ! Merci !
![image](https://user-images.githubusercontent.com/10322028/34572970-2fe90e08-f173-11e7-9647-fd1737c03414.png)

**Comment by DavidBruant** [comment]
👍
