### ISSUE TITLE
xmldom error fichier dm2

### ISSUE THREAD

**Issue by akakeronos** [dtc-innovation/anonymisation-document-budgetaire#22]
Sur les fichiers de la DM2 j'ai l'erreur suivante. Cependant les fichiers ont bien été produits.
Dans ces fichiers DM2 je ne vois pas de CodNatJurBenef.
Je te dépose un exemple ?

D:\cloud\boxGironde\FLUX-XML-TOTEM>anon-doc-budg --in DM2  --out DM2-anon
files [ 'DM22012BPAL.xml',
  'DM22012CDR.xml',
  'DM22012DDL.xml',
  'DM22012DTM.xml',
  'DM22012GER.xml',
  'DM22012LDA.xml',
  'DM22013BPAL.xml',
  'DM22013CDR.xml',
  'DM22013DDL.xml',
  'DM22013DTM.xml',
  'DM22013LDA.xml',
  'DM22014BPAL.xml',
  'DM22014DDL.xml',
  'DM22014DTM.xml',
  'DM22014GER.xml',
  'DM22014LDA.xml',
  'DM22015BPAL.xml',
  'DM22015CDR.xml',
  'DM22015DDL.xml',
  'DM22015DTM.xml',
  'DM22015GER.xml',
  'DM22015LDA.xml',
  'DM22016BPAL.xml',
  'DM22016CDR.xml',
  'DM22016DDL.xml',
  'DM22016DTM.xml',
  'DM22016LDA.xml',
  'DM22017BPAL.xml',
  'DM22017CDR.xml',
  'DM22017DDL.xml',
  'DM22017DTM.xml',
  'DM22017GER.xml',
  'DM22017LDA.xml' ]
[xmldom error]  element parse error: Error: invalid tagName:@#[line:15,col:7]

**Comment by DavidBruant** [comment]
Je viens de publier une nouvelle version de l'outil qui devrait donner le nom du premier fichier qui pose problème. Pour mettre à jour : `npm update anon-doc-budg -g`

**Comment by akakeronos** [comment]
j'ai mis à jour et relancé

[xmldom error]  element parse error: Error: invalid tagName:@#[line:15,col:7]
Anonymized 33 files successfully!

**Comment by DavidBruant** [comment]
> Anonymized 33 files successfully!

Cette ligne informe que l'anonymisation a bien eu lieu et que tous les fichiers ont été générés.

> [xmldom error] element parse error: Error: invalid tagName:@#[line:15,col:7]

J'ai trouvé le fichier qui génère cette erreur, il s'agit de `DM22017CDR.xml` (aucun autre fichier ne génère cette erreur). 

Ligne 15, on peut lire `< ="22330001300016"/>` qui n'est effectivement pas du XML valide (les autres fichiers ont une ligne qui ressemble à `<IdColl V="22330001300750"/>`).

Un parser qui se conforme à la spécification XML devrait jeter une exception à cet endroit. Là, il semble que le parser utilisé ([xmldom](https://www.npmjs.com/package/xmldom)) choisisse d'émettre une erreur dans la console, mais de parser quand même (tant mieux pour nous). 
Dans le fichier anonymisé, on peut voir `&lt;` à la place du `<` suggérant que le parser choisi d'interpréter l'élément cassé comme du texte, ce qui n'est pas gravissime, mais n'est pas non plus un `DocumentBudgetaire` valide.

La bonne solution est de réparer le fichier d'origine (rajouter le `IdColl`) et tout ira bien.

Toutefois ce fichier est assez surprenant. 
Est-ce que quelqu'un a touché les fichiers à la main ? 
S'agit-il d'un bug dans le logiciel Totem ?

**Comment by akakeronos** [comment]
Carine Morin m'a renvoyé un nouvel export du fichier qui n'était pas du XML valide et le IdColl était bien présent. Problème clôturé :)
