### ISSUE TITLE
Faire un benchmark

### ISSUE THREAD

**Issue by DavidBruant** [dtc-innovation/anonymisation-document-budgetaire#35]
Ça prend combien de temps d'anonymiser 2000 fichiers ?

**Comment by oncletom** [comment]
Ça serait marrant si ça prenait moins de temps que pour rédiger un [email qui indique c'est humainement et techniquement pas possible](https://forum.ouvre-boite.org/t/fichiers-xml-des-documents-budgetaires-des-collectivites/227/18).

**Comment by DavidBruant** [comment]
J'avoue :-p

**Comment by DavidBruant** [comment]
Benchmark ici : https://github.com/dtc-innovation/anonymisation-document-budgetaire/pull/37

Rapport de benchmark ici : https://github.com/dtc-innovation/anonymisation-document-budgetaire/blob/master/benchmark/explorations.md

Résumé : 
- sur ma machine, ça anonymise ~10 fichiers par minute
- le process crash à 80 fichiers à anonymiser
