### ISSUE TITLE
Des noms de personnes physiques dans <ORGANISME_ENG>

### ISSUE THREAD

**Issue by DavidBruant** [dtc-innovation/anonymisation-document-budgetaire#7]
Dans un fichier trouvé, il n'y a pas plus précis que `<NatJurOrgEng V="Autres"/>` pour les trouver. Mais [le champ est à valeur ouverte](http://odm-budgetaire.org/doc-schema/Class_OrganismeEng_xsd_Complex_Type_TOrganismeEng.html#TOrganismeEng_NatJurOrgEng), donc dur d'être sûr de trouver une solution interopérable.

**Comment by DavidBruant** [comment]
Non pertinent

**Comment by oncletom** [comment]
Qu'entends-tu par "non pertinent" ?
